//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Details = new HashSet<Order_Detail>();
        }
    
        public int OrderID { get; set; }

        [DisplayName("Customer")]
        [StringLength(1, ErrorMessage = "must be a valid customer id")]
        public string CustomerID { get; set; }

        [DisplayName("Employee")]
        public Nullable<int> EmployeeID { get; set; }

        [DisplayName("Order Date")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.DateTime, ErrorMessage = "must be a date")]
        public Nullable<System.DateTime> OrderDate { get; set; }

        [DisplayName("Required Date")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.DateTime, ErrorMessage = "must be a date")]
        public Nullable<System.DateTime> RequiredDate { get; set; }

        [DisplayName("Shipped Date")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.DateTime, ErrorMessage = "must be a date")]
        public Nullable<System.DateTime> ShippedDate { get; set; }

        [DisplayName("Shipped Via")]
        [Range(0, int.MaxValue, ErrorMessage = "must be a valid shipper")]
        public Nullable<int> ShipVia { get; set; }

        [DisplayName("Freight")]
        public Nullable<decimal> Freight { get; set; }

        [DisplayName("Where To")]
        [StringLength(1, ErrorMessage = "must be a valid customer id")]
        public string ShipName { get; set; }

        [DisplayName("Address")]
        [StringLength(1, ErrorMessage = "must be a valid customer id")]
        public string ShipAddress { get; set; }

        [DisplayName("City")]
        [StringLength(1, ErrorMessage = "must be a valid customer id")]
        public string ShipCity { get; set; }

        [DisplayName("Region")]
        [StringLength(1, ErrorMessage = "must be a valid customer id")]
        public string ShipRegion { get; set; }

        [DisplayName("Postal Code")]
        [StringLength(1, ErrorMessage = "must be a valid customer id")]
        public string ShipPostalCode { get; set; }

        [DisplayName("Country")]
        [StringLength(1, ErrorMessage = "must be a valid customer id")]
        public string ShipCountry { get; set; }

        [DisplayName("Customer")]    
        public virtual Customer Customer { get; set; }

        [DisplayName("Employee")]    
        public virtual Employee Employee { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Details { get; set; }

        [DisplayName("Shipper")]
        public virtual Shipper Shipper { get; set; }
    }
}
