//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Details = new HashSet<Order_Detail>();
        }

        [DisplayName("Id")]
        [Range(0, int.MaxValue, ErrorMessage = "must be a valid interger")]
        public int ProductID { get; set; }

        [DisplayName("Product Name")]
        [StringLength(2, ErrorMessage = "this field must be longer than 2")]
        public string ProductName { get; set; }

        [DisplayName("Supplier Id")]
        [Range(0, int.MaxValue, ErrorMessage = "must be a valid integer")]
        public Nullable<int> SupplierID { get; set; }

        [DisplayName("Category Id")]
        [Range(0, int.MaxValue, ErrorMessage = "must be a valid integer")]
        public Nullable<int> CategoryID { get; set; }

        [DisplayName("Quantity per unit")]
        public string QuantityPerUnit { get; set; }

        [DisplayName("Price per unit")]
        public Nullable<decimal> UnitPrice { get; set; }

        [DisplayName("Units in stock")]
        public Nullable<short> UnitsInStock { get; set; }

        [DisplayName("Units already orderd")]
        public Nullable<short> UnitsOnOrder { get; set; }

        [DisplayName("Reorder Level")]
        public Nullable<short> ReorderLevel { get; set; }

        [DisplayName("Discontinued")]
        public bool Discontinued { get; set; }

        [DisplayName("Category")]    
        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Details { get; set; }

        [DisplayName("Supplier")]
        public virtual Supplier Supplier { get; set; }
    }
}
