//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Territory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Territory()
        {
            this.Employees = new HashSet<Employee>();
        }

        [DisplayName("ID")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "must be between 2 and 50 characters")]
        public string TerritoryID { get; set; }

        [DisplayName("Description")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "must be between 2 and 50 characters")]
        public string TerritoryDescription { get; set; }

        [DisplayName("Region ID")]
        [Range(0, int.MaxValue, ErrorMessage = "must be a valid integer")]
        public int RegionID { get; set; }
    
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
